<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Fri, 12 Feb 2016 08:21:24 +0000
 */

$conf['title'] = 'Big';
$conf['lang'] = 'fr';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
